"""add disease_age_tips table for age-group diet charts

Revision ID: a33f957ca631
Revises: 175df5eff4af
Create Date: 2026-09-22 08:18:32.996789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a33f957ca631'
down_revision: Union[str, None] = '175df5eff4af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disease_age_tips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disease_id', sa.Integer(), nullable=False),
    sa.Column('age_group', sa.Enum('children', 'teen', 'adult', 'senior', name='agegroup'), nullable=False),
    sa.Column('diet_dos', sa.Text(), nullable=True),
    sa.Column('diet_donts', sa.Text(), nullable=True),
    sa.Column('general_tips', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['disease_id'], ['diseases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('disease_id', 'age_group')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('disease_age_tips')
    # ### end Alembic commands ###
